// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace KaemikaMAC
{
	public partial class PreferencesSettingsController : NSViewController
	{
		public PreferencesSettingsController (IntPtr handle) : base (handle)
		{
		}
	}
}
